services:
  postgres:
    image: postgres:17
    container_name: postgres_container
    env_file:
      - ../.env
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - ./pgdata/urls_data:/var/lib/postgresql/data
    networks:
      - app_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d urls"]
      interval: 3s
      timeout: 3s
      retries: 5
  
  url_app:
    container_name: url_app
    build:
      context: ..
      dockerfile: cmd/Dockerfile
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    env_file:
      - ../.env
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app_net
    restart: always
    # develop:
    #   watch:
    #     - path: ../internal
    #       action: rebuild
    #     - path: ../pkg
    #       action: rebuild
    #     - path: ../build/package/server
    #       action: rebuild
    #     - path: ../congigs
    #       action: rebuild
    #     - path: ../cmd
    #       action: rebuild
    #     - path: ../deployments/docker-compose.yml
    #       action: rebuild

  # nginx:
  #   container_name: nginx
  #   build:
  #     context: ..
  #     dockerfile: build/package/nginx/Dockerfile
  #   volumes:
  #     - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
  #   ports:
  #     - "80:80"
  #   depends_on:
  #     - server
  #   networks:
  #     - app_net

volumes:
  pgdata:

networks:
  app_net:
    driver: bridge