global:
  scrape_interval: 1s # Как часто собирать метрики (для локальной разработки ставим почаще)

scrape_configs:
  # 1. Метрики твоего Go-приложения
  - job_name: 'go-app'
    static_configs:
      - targets: ['url_app:2112']

  # 2. Метрики самой Кафки (через экспортер)
  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka-exporter:9308']

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']

  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']