{
 "title": "Postgres",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Current Active Connections",
   "type": "timeseries",
   "description": "Сколько клиентов сейчас подключено к базе.\nЕсли график приближается к лимиту max_connections, новые запросы начнут падать с ошибкой.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(pg_stat_database_numbackends)",
     "legendFormat": "Connections"
    }
   ]
  },
  {
   "title": "Database Transactions Rate",
   "type": "timeseries",
   "description": "Количество успешных транзакций (commits) против отмененных (rollbacks) в секунду.\nВсплеск роллбэков сигнализирует об ошибках в коде приложения или блокировках в БД.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(pg_stat_database_xact_commit[5m]))",
     "legendFormat": "Commits"
    },
    {
     "expr": "sum(rate(pg_stat_database_xact_rollback[5m]))",
     "legendFormat": "Rollbacks"
    }
   ]
  },
  {
   "title": "PostgreSQL Cache Hit Ratio",
   "type": "timeseries",
   "description": "Процент запросов, прочитанных из оперативной памяти (кэша), а не с медленного диска.\nВ идеале показатель должен быть стабильно выше 95-99%.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(pg_stat_database_blks_hit[5m])) / (sum(rate(pg_stat_database_blks_hit[5m])) + sum(rate(pg_stat_database_blks_read[5m]))) * 100",
     "legendFormat": "Cache rate %"
    }
   ]
  },
  {
   "title": "Database Size (mb)",
   "type": "timeseries",
   "description": "Общий физический размер базы данных на диске, включая все таблицы и индексы.\nПомогает прогнозировать свободное место на сервере.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "pg_database_size_bytes{datname='urls'} /1024 /1024",
     "legendFormat": "Used Memory"
    }
   ]
  }
 ]
}