{
 "title": "Home Overview",
 "tags": [
  "home",
  "postgres",
  "kafka"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "HTTP Metrics(RED)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "HTTP Request Rate (RPS)",
   "type": "timeseries",
   "description": "Количество входящих HTTP-запросов в секунду в разрезе методов и путей.\nПоказывает текущую нагрузку на сервис.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{method!~'CONNECT|TRACE', path!='GET /{$}'}[5m])) by (method, path)",
     "legendFormat": "{{method}} {{path}}"
    }
   ]
  },
  {
   "title": "HTTP Error Rate (5xx/4xx)",
   "type": "timeseries",
   "description": "Процент ошибочных ответов сервера от общего числа запросов.\nПомогает мгновенно увидеть деградацию сервиса после деплоя.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 1 },
   "targets": [
    {
     "expr": "(sum(rate(http_requests_total{code=~\"4..|5..\", job=\"go-app\"}[5m])) by (code) / ignoring(code) group_left sum(rate(http_requests_total{job=\"go-app\"}[5m]))) * 100 or on(code) vector(0)",
     "legendFormat": "Error Rate %"
    }
   ]
  },
  {
   "title": "HTTP Latency (p99/p95/p50)",
   "type": "timeseries",
   "description": "Время обработки запросов сервером (перцентили).\nПоказывает реальную скорость работы: например, p99 означает, что 99% пользователей получили ответ быстрее этого значения.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_request_duration_seconds_bucket[5m])) by (le))",
     "legendFormat": "p99 (99%)"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket[5m])) by (le))",
     "legendFormat": "p95 (95%)"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(http_request_duration_seconds_bucket[5m])) by (le))",
     "legendFormat": "p50 (Median)"
    }
   ]
  },
  { "title": "Message Broker (Kafka Metrics)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Active Consumer Groups",
   "type": "stat",
   "description": "Сколько независимых приложений или воркеров сейчас читают Kafka.",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 9 },
   "targets": [
    { "expr": "kafka_consumergroup_members" }
   ]
  },
  {
   "title": "Kafka Traffic (Messages/sec)",
   "type": "timeseries",
   "description": "Сколько сообщений в секунду залетает в каждый топик.\nЕсли график ушел в ноль при живых пользователях — отвалился Producer.",
   "gridPos": { "h": 7, "w": 8, "x": 4, "y": 9 },
   "targets": [
    {
     "expr": "sum(rate(kafka_topic_partition_current_offset[1m])) by (topic)"
    }
   ]
  },
  {
   "title": "Consumer Group Lag (Unprocessed Messages)",
   "type": "timeseries",
   "description": "Сколько сообщений приложение успело получить в Kafka, но еще не успело вычитать и обработать. Если график постоянно сильно растет, то приложение не справляется",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "sum(kafka_consumergroup_lag) by (consumergroup, topic)"
    }
   ]
  },
  { "title": "PostgreSQL Database Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Database Transactions Rate",
   "type": "timeseries",
   "description": "Количество успешных транзакций (commits) против отмененных (rollbacks) в секунду.\nВсплеск роллбэков сигнализирует об ошибках в коде приложения или блокировках в БД.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sum(rate(pg_stat_database_xact_commit[5m]))",
     "legendFormat": "Commits"
    },
    {
     "expr": "sum(rate(pg_stat_database_xact_rollback[5m]))",
     "legendFormat": "Rollbacks"
    }
   ]
  }
 ]
}