{
 "title": "Kafka",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Kafka Traffic (Messages/sec)",
   "type": "timeseries",
   "description": "Сколько сообщений в секунду залетает в каждый топик.\nЕсли график ушел в ноль при живых пользователях — отвалился Producer.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(kafka_topic_partition_current_offset[1m])) by (topic)"
    }
   ]
  },
  {
   "title": "Consumer Group Lag (Unprocessed Messages)",
   "type": "timeseries",
   "description": "Сколько сообщений приложение успело получить в Kafka, но еще не успело вычитать и обработать. Если график постоянно сильно растет, то приложение не справляется",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(kafka_consumergroup_lag) by (consumergroup, topic)"
    }
   ]
  },
  {
   "title": "Total Messages in Topics",
   "type": "stat",
   "description": "Общее накопительное количество сообщений",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(kafka_topic_partition_current_offset) by (topic)"
    }
   ]
  },
  {
   "title": "Topic Partitions Count",
   "type": "bargauge",
   "description": "Кол-во партиций для каждого топика.",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 8 },
   "targets": [
    { "expr": "kafka_topic_partitions" }
   ]
  },
  {
   "title": "Active Consumer Groups",
   "type": "stat",
   "description": "Сколько независимых приложений или воркеров сейчас читают Kafka.",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 8 },
   "targets": [
    { "expr": "kafka_consumergroup_members" }
   ]
  },
  {
   "title": "Exporter Status",
   "type": "stat",
   "description": "Жив ли сам сборщик метрик. Выдает 1 (UP), если Prometheus успешно до него достучался, и 0 (DOWN), если связь оборвалась.",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 8 },
   "targets": [
    {
     "expr": "up{job=\"kafka\"}"
    }
   ]
  }
 ]
}