{
 "title": "Redis",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Redis Connected Clients",
   "type": "timeseries",
   "description": "Количество активных сетевых соединений от вашего Go-приложения к Redis в данный момент.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    { "expr": "redis_connected_clients", "legendFormat": "Connections" }
   ]
  },
  {
   "title": "Redis Memory Usage",
   "type": "timeseries",
   "description": "Объем оперативной памяти, занятый данными в Redis, по отношению к максимальному лимиту.\nЕсли память заполнится, Redis начнет удалять ключи или выдавать ошибки записи.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "redis_memory_used_bytes /1024 /1024",
     "legendFormat": "Used Memory"
    },
    { "expr": "redis_memory_max_bytes", "legendFormat": "Max Memory Limit" }
   ]
  },
  {
   "title": "Redis Cache Hit Ratio",
   "type": "timeseries",
   "description": "Эффективность кэширования в процентах.\nПоказывает, как часто приложение находит нужный ключ в Redis (Hit) по сравнению с промахами (Miss).",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "rate(redis_keyspace_hits_total[5m]) / (rate(redis_keyspace_hits_total[5m]) + rate(redis_keyspace_misses_total[5m])) * 100",
     "legendFormat": "Cache rate %"
    }
   ]
  },
  {
   "title": "Redis Uptime (min)",
   "type": "timeseries",
   "description": "Время непрерывной работы контейнера Redis в секундах.\nЕсли график резко падает в ноль — контейнер перезапускался (например, упал из-за нехватки памяти OOM).",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    { "expr": "redis_uptime_in_seconds / 60", "legendFormat": "minutes alive" }
   ]
  }
 ]
}