name: build.yml
on:
  push:
    branches:
      - main
      - fix/*
      - feat/*

jobs:
  build:
    name: Build Project
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build Docker images
        run: |
          touch .env
          cp env.example .env
          mkdir deployments/pgdata
          docker compose -f deployments/docker-compose.yaml --env-file .env up -d --build